apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer
spec:
  selector:
    matchLabels:
      app: summarizer
  replicas: 1
  template:
    metadata:
      labels:
        app: summarizer
    spec:
      containers:
      - image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ray-demo:latest
        imagePullPolicy: Always
        name: summarizer
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
