apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-cluster-ingress
  namespace: ray-cluster
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: ray-demo.${hostname}
    http:
      paths:
      - path: /dashboard(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: example-cluster-ray-head
            port:
              number: 8265
      - path: /serve(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: example-cluster-ray-head
            port:
              number: 8000